name: bonfire_server
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  shared_events:
    path: ../../shared_events
  tiledjsonreader:
    git:
      url: https://github.com/RafaelBarbosatec/tiled_json_reader.git
      ref: without-flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0