name: bonfire_socket_server
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bonfire_socket_shared:
    path: ../bonfire_socket_shared
  dart_frog: ^1.0.0
  dart_frog_web_socket: ^1.0.0
  uuid: ^3.0.6
  

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0