name: bonfire_multiplayer
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  bonfire: ^3.13.3
  bonfire_bloc: ^0.0.2
  flutter_bloc: ^8.1.3
  shared_events:
    path: "../shared_events"
  equatable: ^2.0.5
  http: ^1.2.2
  get_it: ^8.0.3
  bonfire_socket_client:
    path: "../packages/bonfire_socket_client"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
